### ISSUE TITLE
Khảo sát khách hàng

### ISSUE THREAD

**Issue by hoangvantuan** [HEDSPI-BK-K56/orange#22]
# Khảo sát khách hàng

**Comment by hoangtuan1401** [comment]
![image](https://user-images.githubusercontent.com/30333390/28742768-2c4ba91e-7463-11e7-89f3-a38902cbb208.png)

**Comment by hoangvantuan** [comment]
text ra vào tài liệu nhé

**Comment by hoangvantuan** [comment]
@hoangtuan1401 Cần làm rõ một số điểm sau nhé.
* Với việc bán hàng trên fb thì hóa đơn sẽ được nhập như nào (nhập tay, sử dụng tool của fb)

**Comment by hoangtuan1401** [comment]
Bán hàng trên FB thì hóa đơn sẽ lưu bằng 4 con đường:
-Không lưu: đây là trường hợp có nhưng không nhiều,chủ yếu là những cá nhân tự buôn bán 1 mình (nhỏ).
-Nhập tay,lưu dưới dạng giấy.Phải tới 50% số lượng người lưu theo con đường này,số liệu có thể cao hơn nữa.
![image](https://user-images.githubusercontent.com/30333390/28806088-420529a6-7698-11e7-8f36-d2991c0c54ef.png) Đây là mô phỏng số liệu của 1 cửa hàng ae chạy QC,trong khi ae gửi báo cáo cho họ dưới dạng file PDF thì họ gửi lại như thế này =))
-Nhập tay,lưu dưới dạng file excel.Cũng kha khá người làm cách này,nhưng hạn chế của nó vẫn là phải nhập bằng tay,trước ae buôn bán cũng làm bảng excel để tiện theo dõi cùng bill từ hãng gửi vể.
-Nhập máy,dùng tool hỗ trợ.Facebook chưa có công cụ hỗ trợ này những ở VN có tới 2 đơn vị làm về vấn đề này đó là pancaketool và cái mẹ gì nữa không nhớ tên.Các chức năng và database của nó ae nghĩ là khá ổn và hoàn chỉnh đấy,để ae tìm hiểu thêm cho vì 2 công ty này đều có người quen làm.
