### ISSUE TITLE
Đặt tên cho project [Due Date: 2017/07/21]

### ISSUE THREAD

**Issue by hoangvantuan** [HEDSPI-BK-K56/orange#3]
Nếu mọi người không có ý kiến gì thì project sẽ đặt tên là **Orange** nhé.
Đồng ý thì tích vào task nhé, không thì comment

- [x] Hoang Van Tuan a

- [ ] Nguyen Viet Huynh

- [ ] Tran Huy Cong

- [ ] Nguyen Duy Tuan

- [ ] Hoang Van Tuan b

Quyết định: **Orange**

**Comment by hoangtuan1401** [comment]
tại sao lại lấy tên là Orange?

**Comment by hoangvantuan** [comment]
@hoangtuan1401  chằng có nghĩa gì đâu :)) đặt bừa đó
