### ISSUE TITLE
Đặt tên cho team, tổ chức

### ISSUE THREAD

**Issue by hoangvantuan** [HEDSPI-BK-K56/orange#9]
Hiện nay t lấy lên  cho team và tổ chức là **hedspi-friends-k56**
Nếu ae có tên này hay ý nghĩa hơn thì gợi ý nhé.

**Cần thống nhất**
1. Tên tổ chức github
2. Tên team github
3. Tên Team slack 
4. username sử dụng (ví dụ tên-tổ chức-username: BK56-tuanhv)  

Thống nhất 
**HEDSPI BK K56**

**Comment by hoangtuan1401** [comment]
Eagle rồi lấy biểu tượng của tập đoàn phan thị ấy

**Comment by hoangvantuan** [comment]
thế thì thành nhái mất rồi, đặt cái gì có ý nghĩa tí :))

**Comment by hoangtuan1401** [comment]
cái này có thể để từ từ cũng được,đi đâu mà vội :))

**Comment by hoangvantuan** [comment]
cho thống nhất thôi :)) vậy thì giữ như cũ vậy
